- hosts: _master
  become: true
  tasks:
          - name: Copy myd.yml. 
            copy:
                    src: myd.yml
                    dest: /root/myd.yml
          - name: k8s deployment
            command: "kubectl apply -f /root/myd.yml"
